<a href="https://colab.research.google.com/github/krishshah8000/mlproject/blob/master/Flight_predection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [ ]:
df = pd.read_excel("/content/Data_Train.xlsx")
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [ ]:
df['Dep_Time'] = pd.to_datetime(df['Dep_Time'], format='%H:%M')
df['dep_hour'] = df['Dep_Time'].dt.hour
df['dep_min'] = df['Dep_Time'].dt.minute
print("Extracted 'dep_hour' and 'dep_min' columns:")
print(df[['Dep_Time', 'dep_hour', 'dep_min']].head())

Extracted 'dep_hour' and 'dep_min' columns:
             Dep_Time  dep_hour  dep_min
0 1900-01-01 22:20:00        22       20
1 1900-01-01 05:50:00         5       50
2 1900-01-01 09:25:00         9       25
3 1900-01-01 18:05:00        18        5
4 1900-01-01 16:50:00        16       50

In [ ]:
df.drop('Dep_Time', axis=1, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Arrival_Time     10683 non-null  object
 6   Duration         10683 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10683 non-null  object
 9   Price            10683 non-null  int64
 10  dep_hour         10683 non-null  int32
 11  dep_min          10683 non-null  int32
dtypes: int32(2), int64(1), object(9)
memory usage: 918.2+ KB

In [ ]:
df

,Airline,Date_of_Journey,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,dep_hour,dep_min
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,01:10 22 Mar,2h 50m,non-stop,No info,3897,22,20
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2 stops,No info,7662,5,50
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,04:25 10 Jun,19h,2 stops,No info,13882,9,25
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,23:30,5h 25m,1 stop,No info,6218,18,5
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,21:35,4h 45m,1 stop,No info,13302,16,50
...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,22:25,2h 30m,non-stop,No info,4107,19,55
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,23:20,2h 35m,non-stop,No info,4145,20,45
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,11:20,3h,non-stop,No info,7229,8,20
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,14:10,2h 40m,non-stop,No info,12648,11,30
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,19:15,8h 20m,2 stops,No info,11753,10,55

In [ ]:
df['Arrival_Time'] = pd.to_datetime(df['Arrival_Time'], errors='coerce')
df['arr_hour'] = df['Arrival_Time'].dt.hour
df['arr_min'] = df['Arrival_Time'].dt.minute
print("Extracted 'arr_hour' and 'arr_min' columns:")
print(df[['Arrival_Time', 'arr_hour', 'arr_min']].head())

Extracted 'arr_hour' and 'arr_min' columns:
         Arrival_Time  arr_hour  arr_min
0 2025-03-22 01:10:00         1       10
1 2025-11-29 13:15:00        13       15
2 2025-06-10 04:25:00         4       25
3 2025-11-29 23:30:00        23       30
4 2025-11-29 21:35:00        21       35

/tmp/ipython-input-3264209510.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Arrival_Time'] = pd.to_datetime(df['Arrival_Time'], errors='coerce')

In [ ]:
df.drop('Arrival_Time', axis=1, inplace=True)
print("Original 'Arrival_Time' column dropped.")
df.info()
df.head()

Original 'Arrival_Time' column dropped.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Duration         10683 non-null  object
 6   Total_Stops      10682 non-null  object
 7   Additional_Info  10683 non-null  object
 8   Price            10683 non-null  int64
 9   dep_hour         10683 non-null  int32
 10  dep_min          10683 non-null  int32
 11  arr_hour         10683 non-null  int32
 12  arr_min          10683 non-null  int32
dtypes: int32(4), int64(1), object(8)
memory usage: 918.2+ KB

,Airline,Date_of_Journey,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,dep_hour,dep_min,arr_hour,arr_min
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,22,20,1,10
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,5,50,13,15
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,25,4,25
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,18,5,23,30
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302,16,50,21,35

# Task
Convert the 'Duration' column into a new numerical column named 'duration_total_minutes', representing the total duration in minutes. Then, remove the original 'Duration' column and display the DataFrame's information and the first few rows to verify these changes.

## Convert Duration to Total Minutes

### Subtask:
Parse the 'Duration' column to extract hours and minutes, then calculate the total duration in minutes and store it in a new column named 'duration_total_minutes'. This will handle cases with only hours, only minutes, or both.

**Reasoning**:
To convert the 'Duration' column into total minutes, I will first define a function to parse the duration strings and extract hours and minutes, then apply this function to create the 'duration_total_minutes' column as instructed.

In [ ]:
def convert_duration_to_minutes(duration):
    total_minutes = 0
    if 'h' in duration:
        parts = duration.split('h')
        total_minutes += int(parts[0].strip()) * 60
        if 'm' in parts[1]:
            total_minutes += int(parts[1].replace('m', '').strip())
    elif 'm' in duration:
        total_minutes += int(duration.replace('m', '').strip())
    return total_minutes

df['duration_total_minutes'] = df['Duration'].apply(convert_duration_to_minutes)
print("Created 'duration_total_minutes' column:")
print(df[['Duration', 'duration_total_minutes']].head())

Created 'duration_total_minutes' column:
  Duration  duration_total_minutes
0   2h 50m                     170
1   7h 25m                     445
2      19h                    1140
3   5h 25m                     325
4   4h 45m                     285

**Reasoning**:
Now that the 'duration_total_minutes' column has been created, I will remove the original 'Duration' column as instructed. Then, I will display the DataFrame's information and the first few rows to verify the changes.

In [ ]:
df.drop('Duration', axis=1, inplace=True)
print("Original 'Duration' column dropped.")
df.info()
df.head()

Original 'Duration' column dropped.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Airline                 10683 non-null  object
 1   Date_of_Journey         10683 non-null  object
 2   Source                  10683 non-null  object
 3   Destination             10683 non-null  object
 4   Route                   10682 non-null  object
 5   Total_Stops             10682 non-null  object
 6   Additional_Info         10683 non-null  object
 7   Price                   10683 non-null  int64
 8   dep_hour                10683 non-null  int32
 9   dep_min                 10683 non-null  int32
 10  arr_hour                10683 non-null  int32
 11  arr_min                 10683 non-null  int32
 12  duration_total_minutes  10683 non-null  int64
dtypes: int32(4), int64(2), object(7)
memory usage: 918.2+ KB

,Airline,Date_of_Journey,Source,Destination,Route,Total_Stops,Additional_Info,Price,dep_hour,dep_min,arr_hour,arr_min,duration_total_minutes
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,non-stop,No info,3897,22,20,1,10,170
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,2 stops,No info,7662,5,50,13,15,445
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,2 stops,No info,13882,9,25,4,25,1140
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,1 stop,No info,6218,18,5,23,30,325
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,1 stop,No info,13302,16,50,21,35,285

## Convert 'Total_Stops' to numerical

### Subtask:
Convert the 'Total_Stops' column from string format to a numerical integer column. 'non-stop' should be converted to `0`, '1 stop' to `1`, and so on. Also, handle the single null value by filling it with `0` (assuming 'non-stop').

In [ ]:
def convert_total_stops(stops):
    if pd.isna(stops):
        return 0  # Assuming a NaN value means no stops
    if stops == 'non-stop':
        return 0
    return int(stops.split(' ')[0])

df['Total_Stops'] = df['Total_Stops'].apply(convert_total_stops)
print("Converted 'Total_Stops' column:")
print(df[['Total_Stops']].head())
df.info()

Converted 'Total_Stops' column:
   Total_Stops
0            0
1            2
2            2
3            1
4            1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Airline                 10683 non-null  object
 1   Date_of_Journey         10683 non-null  object
 2   Source                  10683 non-null  object
 3   Destination             10683 non-null  object
 4   Route                   10682 non-null  object
 5   Total_Stops             10683 non-null  int64
 6   Additional_Info         10683 non-null  object
 7   Price                   10683 non-null  int64
 8   dep_hour                10683 non-null  int32
 9   dep_min                 10683 non-null  int32
 10  arr_hour                10683 non-null  int32
 11  arr_min                 10683 non-null  int32
 12  duration_total_minutes  10683 non-null  int64
dtypes: int32(4), int64(3), object(6)
memory usage: 918.2+ KB

In [ ]:
df

,Airline,Date_of_Journey,Source,Destination,Route,Total_Stops,Additional_Info,Price,dep_hour,dep_min,arr_hour,arr_min,duration_total_minutes
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,0,No info,3897,22,20,1,10,170
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,2,No info,7662,5,50,13,15,445
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,2,No info,13882,9,25,4,25,1140
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,1,No info,6218,18,5,23,30,325
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,1,No info,13302,16,50,21,35,285
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,0,No info,4107,19,55,22,25,150
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,0,No info,4145,20,45,23,20,155
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,0,No info,7229,8,20,11,20,180
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,0,No info,12648,11,30,14,10,160
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,2,No info,11753,10,55,19,15,500

In [ ]:
df.drop('Route', axis=1, inplace=True)

KeyError: "['Route'] not found in axis"

In [ ]:
df

,Airline,Date_of_Journey,Source,Destination,Total_Stops,Additional_Info,Price,dep_hour,dep_min,arr_hour,arr_min,duration_total_minutes
0,IndiGo,24/03/2019,Banglore,New Delhi,0,No info,3897,22,20,1,10,170
1,Air India,1/05/2019,Kolkata,Banglore,2,No info,7662,5,50,13,15,445
2,Jet Airways,9/06/2019,Delhi,Cochin,2,No info,13882,9,25,4,25,1140
3,IndiGo,12/05/2019,Kolkata,Banglore,1,No info,6218,18,5,23,30,325
4,IndiGo,01/03/2019,Banglore,New Delhi,1,No info,13302,16,50,21,35,285
...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,0,No info,4107,19,55,22,25,150
10679,Air India,27/04/2019,Kolkata,Banglore,0,No info,4145,20,45,23,20,155
10680,Jet Airways,27/04/2019,Banglore,Delhi,0,No info,7229,8,20,11,20,180
10681,Vistara,01/03/2019,Banglore,New Delhi,0,No info,12648,11,30,14,10,160
10682,Air India,9/05/2019,Delhi,Cochin,2,No info,11753,10,55,19,15,500

## Convert 'Date_of_Journey' to numerical components

### Subtask:
Convert the 'Date_of_Journey' column into separate integer columns for day, month, and year.

In [ ]:
df['Date_of_Journey'] = pd.to_datetime(df['Date_of_Journey'], format='%d/%m/%Y')
df['journey_day'] = df['Date_of_Journey'].dt.day
df['journey_month'] = df['Date_of_Journey'].dt.month
df['journey_year'] = df['Date_of_Journey'].dt.year

print("Extracted 'journey_day', 'journey_month', and 'journey_year' columns:")
print(df[['Date_of_Journey', 'journey_day', 'journey_month', 'journey_year']].head())
df.info()

Extracted 'journey_day', 'journey_month', and 'journey_year' columns:
  Date_of_Journey  journey_day  journey_month  journey_year
0      2019-03-24           24              3          2019
1      2019-05-01            1              5          2019
2      2019-06-09            9              6          2019
3      2019-05-12           12              5          2019
4      2019-03-01            1              3          2019
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Airline                 10683 non-null  object
 1   Date_of_Journey         10683 non-null  datetime64[ns]
 2   Source                  10683 non-null  object
 3   Destination             10683 non-null  object
 4   Total_Stops             10683 non-null  int64
 5   Additional_Info         10683 non-null  object
 6   Price                   10683 non-null  int64
 7   dep_hour                10683 non-null  int32
 8   dep_min                 10683 non-null  int32
 9   arr_hour                10683 non-null  int32
 10  arr_min                 10683 non-null  int32
 11  duration_total_minutes  10683 non-null  int64
 12  journey_day             10683 non-null  int32
 13  journey_month           10683 non-null  int32
 14  journey_year            10683 non-null  int32
dtypes: datetime64[ns](1), int32(7), int64(3), object(4)
memory usage: 959.9+ KB

In [ ]:
df

,Airline,Date_of_Journey,Source,Destination,Total_Stops,Additional_Info,Price,dep_hour,dep_min,arr_hour,arr_min,duration_total_minutes,journey_day,journey_month,journey_year
0,IndiGo,2019-03-24,Banglore,New Delhi,0,No info,3897,22,20,1,10,170,24,3,2019
1,Air India,2019-05-01,Kolkata,Banglore,2,No info,7662,5,50,13,15,445,1,5,2019
2,Jet Airways,2019-06-09,Delhi,Cochin,2,No info,13882,9,25,4,25,1140,9,6,2019
3,IndiGo,2019-05-12,Kolkata,Banglore,1,No info,6218,18,5,23,30,325,12,5,2019
4,IndiGo,2019-03-01,Banglore,New Delhi,1,No info,13302,16,50,21,35,285,1,3,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,2019-04-09,Kolkata,Banglore,0,No info,4107,19,55,22,25,150,9,4,2019
10679,Air India,2019-04-27,Kolkata,Banglore,0,No info,4145,20,45,23,20,155,27,4,2019
10680,Jet Airways,2019-04-27,Banglore,Delhi,0,No info,7229,8,20,11,20,180,27,4,2019
10681,Vistara,2019-03-01,Banglore,New Delhi,0,No info,12648,11,30,14,10,160,1,3,2019
10682,Air India,2019-05-09,Delhi,Cochin,2,No info,11753,10,55,19,15,500,9,5,2019

In [ ]:
df.drop('Date_of_Journey', axis=1, inplace=True)

In [ ]:
print(df['Airline'].unique())
print(df['Source'].unique())
print(df['Destination'].unique())
print(df['Additional_Info'].unique())

['IndiGo' 'Air India' 'Jet Airways' 'SpiceJet' 'Multiple carriers' 'GoAir'
 'Vistara' 'Air Asia' 'Vistara Premium economy' 'Jet Airways Business'
 'Multiple carriers Premium economy' 'Trujet']
['Banglore' 'Kolkata' 'Delhi' 'Chennai' 'Mumbai']
['New Delhi' 'Banglore' 'Cochin' 'Kolkata' 'Delhi' 'Hyderabad']
['No info' 'In-flight meal not included' 'No check-in baggage included'
 '1 Short layover' 'No Info' '1 Long layover' 'Change airports'
 'Business class' 'Red-eye flight' '2 Long layover']

## Applying Label Encoding for Demonstration

**Note**: The columns 'Airline', 'Source', 'Destination', and 'Additional_Info' in your main `df` have already been one-hot encoded. To demonstrate Label Encoding on these original columns, I will create a new temporary DataFrame (`df_le`) by reloading the raw data and applying prior preprocessing steps (like converting 'Total_Stops' and extracting date components) before applying Label Encoding. This ensures your current `df` remains unchanged.

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Create a fresh DataFrame copy to demonstrate Label Encoding
df_le = pd.read_excel("/content/Data_Train.xlsx")

# --- Reapply previous preprocessing steps to df_le ---

# Handle Dep_Time
df_le['Dep_Time'] = pd.to_datetime(df_le['Dep_Time'], format='%H:%M')
df_le['dep_hour'] = df_le['Dep_Time'].dt.hour
df_le['dep_min'] = df_le['Dep_Time'].dt.minute
df_le.drop('Dep_Time', axis=1, inplace=True)

# Handle Arrival_Time
df_le['Arrival_Time'] = pd.to_datetime(df_le['Arrival_Time'], errors='coerce')
df_le['arr_hour'] = df_le['Arrival_Time'].dt.hour
df_le['arr_min'] = df_le['Arrival_Time'].dt.minute
df_le.drop('Arrival_Time', axis=1, inplace=True)

# Handle Duration
def convert_duration_to_minutes(duration):
    total_minutes = 0
    if 'h' in duration:
        parts = duration.split('h')
        total_minutes += int(parts[0].strip()) * 60
        if 'm' in parts[1]:
            total_minutes += int(parts[1].replace('m', '').strip())
    elif 'm' in duration:
        total_minutes += int(duration.replace('m', '').strip())
    return total_minutes
df_le['duration_total_minutes'] = df_le['Duration'].apply(convert_duration_to_minutes)
df_le.drop('Duration', axis=1, inplace=True)

# Handle Total_Stops
def convert_total_stops(stops):
    if pd.isna(stops):
        return 0  # Assuming a NaN value means no stops
    if stops == 'non-stop':
        return 0
    return int(stops.split(' ')[0])
df_le['Total_Stops'] = df_le['Total_Stops'].apply(convert_total_stops)

# Handle Date_of_Journey
df_le['Date_of_Journey'] = pd.to_datetime(df_le['Date_of_Journey'], format='%d/%m/%Y')
df_le['journey_day'] = df_le['Date_of_Journey'].dt.day
df_le['journey_month'] = df_le['Date_of_Journey'].dt.month
df_le['journey_year'] = df_le['Date_of_Journey'].dt.year
df_le.drop('Date_of_Journey', axis=1, inplace=True)

# Drop 'Route' column as it was dropped before one-hot encoding
df_le.drop('Route', axis=1, inplace=True)

# --- Apply LabelEncoder to the specified columns ---
label_encoder = LabelEncoder()

for col in ['Airline', 'Source', 'Destination', 'Additional_Info']:
    df_le[col] = label_encoder.fit_transform(df_le[col])

print("DataFrame after Label Encoding:")
df_le.info()
df_le.head()

DataFrame after Label Encoding:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Airline                 10683 non-null  int64
 1   Source                  10683 non-null  int64
 2   Destination             10683 non-null  int64
 3   Total_Stops             10683 non-null  int64
 4   Additional_Info         10683 non-null  int64
 5   Price                   10683 non-null  int64
 6   dep_hour                10683 non-null  int32
 7   dep_min                 10683 non-null  int32
 8   arr_hour                10683 non-null  int32
 9   arr_min                 10683 non-null  int32
 10  duration_total_minutes  10683 non-null  int64
 11  journey_day             10683 non-null  int32
 12  journey_month           10683 non-null  int32
 13  journey_year            10683 non-null  int32
dtypes: int32(7), int64(7)
memory usage: 876.5 KB

/tmp/ipython-input-3123179241.py:16: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_le['Arrival_Time'] = pd.to_datetime(df_le['Arrival_Time'], errors='coerce')

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,dep_hour,dep_min,arr_hour,arr_min,duration_total_minutes,journey_day,journey_month,journey_year
0,3,0,5,0,8,3897,22,20,1,10,170,24,3,2019
1,1,3,0,2,8,7662,5,50,13,15,445,1,5,2019
2,4,2,1,2,8,13882,9,25,4,25,1140,9,6,2019
3,3,3,0,1,8,6218,18,5,23,30,325,12,5,2019
4,3,0,5,1,8,13302,16,50,21,35,285,1,3,2019