<a href="https://colab.research.google.com/github/krishshah8000/mlproject/blob/master/ML_Movie_Genre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd

In [16]:
movieCredit = pd.read_csv('tmdb_5000_credits.csv', usecols=['movie_id', 'title', 'cast', 'crew'], engine='python', skipinitialspace=True)
movieCredit

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...
4828,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4829,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4830,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4831,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4832,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [17]:
duplicate_titles = movieCredit[movieCredit['title'].duplicated(keep=False)]
print("Rows with duplicate titles:")
print(duplicate_titles)

Rows with duplicate titles:
                    movie_id            title  \
29                       NaN              NaN
30                       NaN              NaN
31                  ake-Up""    ""gender"": 0
216                      NaN              NaN
217                      NaN              NaN
225                      NaN              NaN
226                      NaN              NaN
241                      NaN              NaN
242                      NaN              NaN
311                      NaN              NaN
312                      NaN              NaN
313   rtment"": ""Lighting""    ""gender"": 0
428                      NaN              NaN
429                      NaN              NaN
430                Effects""    ""gender"": 0
617                      NaN              NaN
618                      NaN              NaN
659                      NaN              NaN
660                      NaN              NaN
996                    72710         The Host
1158                     NaN              NaN
1159                     NaN              NaN
1386                     268           Batman
2904                    1255         The Host
3674                   39269  Out of the Blue
3720                   10844  Out of the Blue
4244                     NaN              NaN
4245                     NaN              NaN
4297                    2661           Batman

                                                   cast  \
29                                                  NaN
30                                                  NaN
31                                      ""id"": 1463382
216                                                 NaN
217                                                 NaN
225                                                 NaN
226                                                 NaN
241                                                 NaN
242                                                 NaN
311                                                 NaN
312                                                 NaN
313                                     ""id"": 1555031
428                                                 NaN
429                                                 NaN
430                                     ""id"": 1798489
617                                                 NaN
618                                                 NaN
659                                                 NaN
660                                                 NaN
996   [{"cast_id": 52, "character": "Melanie Stryder...
1158                                                NaN
1159                                                NaN
1386  [{"cast_id": 5, "character": "Jack Napier/The ...
2904  [{"cast_id": 3, "character": "Park Gang-du", "...
3674  [{"cast_id": 2, "character": "Don", "credit_id...
3720  [{"cast_id": 12, "character": "Nick Harvey", "...
4244                                                NaN
4245                                                NaN
4297  [{"cast_id": 17, "character": "Batman / Bruce ...

                                                   crew
29                                                  NaN
30                                                  NaN
31                     ""job"": ""Set Dressing Artist""
216                                                 NaN
217                                                 NaN
225                                                 NaN
226                                                 NaN
241                                                 NaN
242                                                 NaN
311                                                 NaN
312                                                 NaN
313                            ""job"": ""Electrician""
428                                                 NaN
429                                                 NaN
430                              ""job"": ""3D Artist""
617                                                 NaN
618                                                 NaN
659                                                 NaN
660                                                 NaN
996   [{"credit_id": "52fe487bc3a368484e0fa919", "de...
1158                                                NaN
1159                                                NaN
1386  [{"credit_id": "52fe422fc3a36847f800aa4b", "de...
2904  [{"credit_id": "52fe42eac3a36847f802ca6b", "de...
3674  [{"credit_id": "52fe47099251416c9106826f", "de...
3720  [{"credit_id": "52fe43c19251416c7501cceb", "de...
4244                                                NaN
4245                                                NaN
4297  [{"credit_id": "52fe4363c3a36847f80509a7", "de...

In [18]:
import json

def extract_cast_names(cast_str):
    try:
        # Ensure the input is a string before attempting to load
        if not isinstance(cast_str, str):
            return ''

        cast_list = json.loads(cast_str)
        names = [member['name'] for member in cast_list if 'name' in member]
        return ', '.join(names)
    except json.JSONDecodeError:
        return '' # Return an empty string if JSON parsing fails
    except Exception as e:
        # Handle other potential errors during processing
        print(f"Error processing cast string: {cast_str} - {e}")
        return ''

movieCredit['cast'] = movieCredit['cast'].apply(extract_cast_names)
print("Extracted cast names and updated 'cast' column in movieCredit DataFrame.")
print(movieCredit.head())

Extracted cast names and updated 'cast' column in movieCredit DataFrame.
  movie_id                                     title  \
0    19995                                    Avatar
1      285  Pirates of the Caribbean: At World's End
2   206647                                   Spectre
3    49026                     The Dark Knight Rises
4    49529                               John Carter

                                                cast  \
0  Sam Worthington, Zoe Saldana, Sigourney Weaver...
1  Johnny Depp, Orlando Bloom, Keira Knightley, S...
2  Daniel Craig, Christoph Waltz, Léa Seydoux, Ra...
3  Christian Bale, Michael Caine, Gary Oldman, An...
4  Taylor Kitsch, Lynn Collins, Samantha Morton, ...

                                                crew
0  [{"credit_id": "52fe48009251416c750aca23", "de...
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2  [{"credit_id": "54805967c3a36829b5002c41", "de...
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [19]:
import json

def extract_department_names(crew_str):
    try:
        # Ensure the input is a string before attempting to load
        if not isinstance(crew_str, str):
            return []

        crew_list = json.loads(crew_str)
        departments = [member['department'] for member in crew_list if 'department' in member]
        return departments
    except json.JSONDecodeError:
        return [] # Return an empty list if JSON parsing fails
    except Exception as e:
        # Handle other potential errors during processing
        print(f"Error processing crew string: {crew_str} - {e}")
        return []

movieCredit['crew_departments'] = movieCredit['crew'].apply(extract_department_names)
print("Extracted crew department names and added 'crew_departments' column in movieCredit DataFrame.")
print(movieCredit.head())

Extracted crew department names and added 'crew_departments' column in movieCredit DataFrame.
  movie_id                                     title  \
0    19995                                    Avatar
1      285  Pirates of the Caribbean: At World's End
2   206647                                   Spectre
3    49026                     The Dark Knight Rises
4    49529                               John Carter

                                                cast  \
0  Sam Worthington, Zoe Saldana, Sigourney Weaver...
1  Johnny Depp, Orlando Bloom, Keira Knightley, S...
2  Daniel Craig, Christoph Waltz, Léa Seydoux, Ra...
3  Christian Bale, Michael Caine, Gary Oldman, An...
4  Taylor Kitsch, Lynn Collins, Samantha Morton, ...

                                                crew  \
0  [{"credit_id": "52fe48009251416c750aca23", "de...
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2  [{"credit_id": "54805967c3a36829b5002c41", "de...
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

                                    crew_departments
0  [Editing, Art, Sound, Sound, Production, Sound...
1  [Camera, Directing, Production, Writing, Writi...
2  [Sound, Directing, Art, Writing, Writing, Art,...
3  [Sound, Production, Writing, Directing, Produc...
4  [Writing, Directing, Crew, Production, Product...

In [20]:
all_departments = movieCredit['crew_departments'].explode().dropna().unique()
print("Unique Department Names:")
print(sorted(all_departments))

Unique Department Names:
['Actors', 'Art', 'Camera', 'Costume & Make-Up', 'Crew', 'Directing', 'Editing', 'Lighting', 'Production', 'Sound', 'Visual Effects', 'Writing']

In [21]:
import json

def extract_directors(crew_str):
    try:
        if not isinstance(crew_str, str):
            return ''
        crew_list = json.loads(crew_str)
        directors = [member['name'] for member in crew_list if member.get('department') == 'Directing' and member.get('job') == 'Director']
        return ', '.join(directors)
    except json.JSONDecodeError:
        return ''
    except Exception as e:
        print(f"Error processing crew string: {crew_str} - {e}")
        return ''

movieCredit['directing_crew'] = movieCredit['crew'].apply(extract_directors)
print("Extracted directing crew names and added 'directing_crew' column in movieCredit DataFrame.")
print(movieCredit.head())

Extracted directing crew names and added 'directing_crew' column in movieCredit DataFrame.
  movie_id                                     title  \
0    19995                                    Avatar
1      285  Pirates of the Caribbean: At World's End
2   206647                                   Spectre
3    49026                     The Dark Knight Rises
4    49529                               John Carter

                                                cast  \
0  Sam Worthington, Zoe Saldana, Sigourney Weaver...
1  Johnny Depp, Orlando Bloom, Keira Knightley, S...
2  Daniel Craig, Christoph Waltz, Léa Seydoux, Ra...
3  Christian Bale, Michael Caine, Gary Oldman, An...
4  Taylor Kitsch, Lynn Collins, Samantha Morton, ...

                                                crew  \
0  [{"credit_id": "52fe48009251416c750aca23", "de...
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2  [{"credit_id": "54805967c3a36829b5002c41", "de...
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

                                    crew_departments     directing_crew
0  [Editing, Art, Sound, Sound, Production, Sound...      James Cameron
1  [Camera, Directing, Production, Writing, Writi...     Gore Verbinski
2  [Sound, Directing, Art, Writing, Writing, Art,...         Sam Mendes
3  [Sound, Production, Writing, Directing, Produc...  Christopher Nolan
4  [Writing, Directing, Crew, Production, Product...     Andrew Stanton

In [22]:
import json

def extract_writers(crew_str):
    try:
        if not isinstance(crew_str, str):
            return ''
        crew_list = json.loads(crew_str)
        writers = [member['name'] for member in crew_list if member.get('department') == 'Writing']
        return ', '.join(writers)
    except json.JSONDecodeError:
        return ''
    except Exception as e:
        print(f"Error processing crew string: {crew_str} - {e}")
        return ''

movieCredit['writing_crew'] = movieCredit['crew'].apply(extract_writers)
print("Extracted writing crew names and added 'writing_crew' column in movieCredit DataFrame.")
print(movieCredit.head())

Extracted writing crew names and added 'writing_crew' column in movieCredit DataFrame.
  movie_id                                     title  \
0    19995                                    Avatar
1      285  Pirates of the Caribbean: At World's End
2   206647                                   Spectre
3    49026                     The Dark Knight Rises
4    49529                               John Carter

                                                cast  \
0  Sam Worthington, Zoe Saldana, Sigourney Weaver...
1  Johnny Depp, Orlando Bloom, Keira Knightley, S...
2  Daniel Craig, Christoph Waltz, Léa Seydoux, Ra...
3  Christian Bale, Michael Caine, Gary Oldman, An...
4  Taylor Kitsch, Lynn Collins, Samantha Morton, ...

                                                crew  \
0  [{"credit_id": "52fe48009251416c750aca23", "de...
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2  [{"credit_id": "54805967c3a36829b5002c41", "de...
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

                                    crew_departments     directing_crew  \
0  [Editing, Art, Sound, Sound, Production, Sound...      James Cameron
1  [Camera, Directing, Production, Writing, Writi...     Gore Verbinski
2  [Sound, Directing, Art, Writing, Writing, Art,...         Sam Mendes
3  [Sound, Production, Writing, Directing, Produc...  Christopher Nolan
4  [Writing, Directing, Crew, Production, Product...     Andrew Stanton

                                        writing_crew
0                       James Cameron, James Cameron
1                          Ted Elliott, Terry Rossio
2  John Logan, John Logan, Ian Fleming, Robert Wa...
3  Christopher Nolan, Christopher Nolan, Jonathan...
4  Andrew Stanton, Edgar Rice Burroughs, Michael ...

In [23]:
movieCredit.drop('crew', axis=1, inplace=True)
print("Original 'crew' column removed.")
print(movieCredit.head())

Original 'crew' column removed.
  movie_id                                     title  \
0    19995                                    Avatar
1      285  Pirates of the Caribbean: At World's End
2   206647                                   Spectre
3    49026                     The Dark Knight Rises
4    49529                               John Carter

                                                cast  \
0  Sam Worthington, Zoe Saldana, Sigourney Weaver...
1  Johnny Depp, Orlando Bloom, Keira Knightley, S...
2  Daniel Craig, Christoph Waltz, Léa Seydoux, Ra...
3  Christian Bale, Michael Caine, Gary Oldman, An...
4  Taylor Kitsch, Lynn Collins, Samantha Morton, ...

                                    crew_departments     directing_crew  \
0  [Editing, Art, Sound, Sound, Production, Sound...      James Cameron
1  [Camera, Directing, Production, Writing, Writi...     Gore Verbinski
2  [Sound, Directing, Art, Writing, Writing, Art,...         Sam Mendes
3  [Sound, Production, Writing, Directing, Produc...  Christopher Nolan
4  [Writing, Directing, Crew, Production, Product...     Andrew Stanton

                                        writing_crew
0                       James Cameron, James Cameron
1                          Ted Elliott, Terry Rossio
2  John Logan, John Logan, Ian Fleming, Robert Wa...
3  Christopher Nolan, Christopher Nolan, Jonathan...
4  Andrew Stanton, Edgar Rice Burroughs, Michael ...

In [24]:
movieCredit.drop('crew_departments', axis=1, inplace=True)
movieCredit

,movie_id,title,cast,directing_crew,writing_crew
0,19995,Avatar,"Sam Worthington, Zoe Saldana, Sigourney Weaver...",James Cameron,"James Cameron, James Cameron"
1,285,Pirates of the Caribbean: At World's End,"Johnny Depp, Orlando Bloom, Keira Knightley, S...",Gore Verbinski,"Ted Elliott, Terry Rossio"
2,206647,Spectre,"Daniel Craig, Christoph Waltz, Léa Seydoux, Ra...",Sam Mendes,"John Logan, John Logan, Ian Fleming, Robert Wa..."
3,49026,The Dark Knight Rises,"Christian Bale, Michael Caine, Gary Oldman, An...",Christopher Nolan,"Christopher Nolan, Christopher Nolan, Jonathan..."
4,49529,John Carter,"Taylor Kitsch, Lynn Collins, Samantha Morton, ...",Andrew Stanton,"Andrew Stanton, Edgar Rice Burroughs, Michael ..."
...,...,...,...,...,...
4828,9367,El Mariachi,"Carlos Gallardo, Jaime de Hoyos, Peter Marquar...",Robert Rodriguez,Robert Rodriguez
4829,72766,Newlyweds,"Edward Burns, Kerry Bishé, Marsha Dietlein, Ca...",Edward Burns,Edward Burns
4830,231617,"Signed, Sealed, Delivered","Eric Mabius, Kristin Booth, Crystal Lowe, Geof...",Scott Smith,Martha Williamson
4831,126186,Shanghai Calling,"Daniel Henney, Eliza Coupe, Bill Paxton, Alan ...",Daniel Hsia,Daniel Hsia
4832,25975,My Date with Drew,"Drew Barrymore, Brian Herzlinger, Corey Feldma...","Brian Herzlinger, Jon Gunn, Brett Winn",

In [25]:
movieCredit

,movie_id,title,cast,directing_crew,writing_crew
0,19995,Avatar,"Sam Worthington, Zoe Saldana, Sigourney Weaver...",James Cameron,"James Cameron, James Cameron"
1,285,Pirates of the Caribbean: At World's End,"Johnny Depp, Orlando Bloom, Keira Knightley, S...",Gore Verbinski,"Ted Elliott, Terry Rossio"
2,206647,Spectre,"Daniel Craig, Christoph Waltz, Léa Seydoux, Ra...",Sam Mendes,"John Logan, John Logan, Ian Fleming, Robert Wa..."
3,49026,The Dark Knight Rises,"Christian Bale, Michael Caine, Gary Oldman, An...",Christopher Nolan,"Christopher Nolan, Christopher Nolan, Jonathan..."
4,49529,John Carter,"Taylor Kitsch, Lynn Collins, Samantha Morton, ...",Andrew Stanton,"Andrew Stanton, Edgar Rice Burroughs, Michael ..."
...,...,...,...,...,...
4828,9367,El Mariachi,"Carlos Gallardo, Jaime de Hoyos, Peter Marquar...",Robert Rodriguez,Robert Rodriguez
4829,72766,Newlyweds,"Edward Burns, Kerry Bishé, Marsha Dietlein, Ca...",Edward Burns,Edward Burns
4830,231617,"Signed, Sealed, Delivered","Eric Mabius, Kristin Booth, Crystal Lowe, Geof...",Scott Smith,Martha Williamson
4831,126186,Shanghai Calling,"Daniel Henney, Eliza Coupe, Bill Paxton, Alan ...",Daniel Hsia,Daniel Hsia
4832,25975,My Date with Drew,"Drew Barrymore, Brian Herzlinger, Corey Feldma...","Brian Herzlinger, Jon Gunn, Brett Winn",

In [26]:
def get_unique_names(names_str):
    if not isinstance(names_str, str) or not names_str.strip():
        return ''
    names = [name.strip() for name in names_str.split(',')]
    unique_names = sorted(list(set(names))) # Sort for consistent output
    return ', '.join(unique_names)

movieCredit['cast'] = movieCredit['cast'].apply(get_unique_names)
print("Applied get_unique_names function to 'cast' column.")
print(movieCredit.head())

Applied get_unique_names function to 'cast' column.
  movie_id                                     title  \
0    19995                                    Avatar
1      285  Pirates of the Caribbean: At World's End
2   206647                                   Spectre
3    49026                     The Dark Knight Rises
4    49529                               John Carter

                                                cast     directing_crew  \
0  Alicia Vela-Bailey, Allan Henry, Anthony Ingru...      James Cameron
1  Andy Beckwith, Angus Barnett, Bill Nighy, Chow...     Gore Verbinski
2  Adam McGrady, Adel Bencherif, Adriana Paz, Ale...         Sam Mendes
3  Aidan Gillen, Aja Evans, Aldous Davidson, Alex...  Christopher Nolan
4  Amanda Clayton, Arkie Reece, Bryan Cranston, C...     Andrew Stanton

                                        writing_crew
0                       James Cameron, James Cameron
1                          Ted Elliott, Terry Rossio
2  John Logan, John Logan, Ian Fleming, Robert Wa...
3  Christopher Nolan, Christopher Nolan, Jonathan...
4  Andrew Stanton, Edgar Rice Burroughs, Michael ...

**Reasoning**:
The subtask requires applying the already defined `get_unique_names` function to the 'directing_crew' column of the `movieCredit` DataFrame to ensure each entry contains only unique names.

In [27]:
movieCredit['directing_crew'] = movieCredit['directing_crew'].apply(get_unique_names)
print("Applied get_unique_names function to 'directing_crew' column.")
print(movieCredit.head())

Applied get_unique_names function to 'directing_crew' column.
  movie_id                                     title  \
0    19995                                    Avatar
1      285  Pirates of the Caribbean: At World's End
2   206647                                   Spectre
3    49026                     The Dark Knight Rises
4    49529                               John Carter

                                                cast     directing_crew  \
0  Alicia Vela-Bailey, Allan Henry, Anthony Ingru...      James Cameron
1  Andy Beckwith, Angus Barnett, Bill Nighy, Chow...     Gore Verbinski
2  Adam McGrady, Adel Bencherif, Adriana Paz, Ale...         Sam Mendes
3  Aidan Gillen, Aja Evans, Aldous Davidson, Alex...  Christopher Nolan
4  Amanda Clayton, Arkie Reece, Bryan Cranston, C...     Andrew Stanton

                                        writing_crew
0                       James Cameron, James Cameron
1                          Ted Elliott, Terry Rossio
2  John Logan, John Logan, Ian Fleming, Robert Wa...
3  Christopher Nolan, Christopher Nolan, Jonathan...
4  Andrew Stanton, Edgar Rice Burroughs, Michael ...

In [28]:
movieCredit['writing_crew'] = movieCredit['writing_crew'].apply(get_unique_names)
print("Applied get_unique_names function to 'writing_crew' column.")
print(movieCredit.head())

Applied get_unique_names function to 'writing_crew' column.
  movie_id                                     title  \
0    19995                                    Avatar
1      285  Pirates of the Caribbean: At World's End
2   206647                                   Spectre
3    49026                     The Dark Knight Rises
4    49529                               John Carter

                                                cast     directing_crew  \
0  Alicia Vela-Bailey, Allan Henry, Anthony Ingru...      James Cameron
1  Andy Beckwith, Angus Barnett, Bill Nighy, Chow...     Gore Verbinski
2  Adam McGrady, Adel Bencherif, Adriana Paz, Ale...         Sam Mendes
3  Aidan Gillen, Aja Evans, Aldous Davidson, Alex...  Christopher Nolan
4  Amanda Clayton, Arkie Reece, Bryan Cranston, C...     Andrew Stanton

                                        writing_crew
0                                      James Cameron
1                          Ted Elliott, Terry Rossio
2  Ian Fleming, Jez Butterworth, John Logan, Neal...
3  Bob Kane, Christopher Nolan, David S. Goyer, J...
4  Andrew Stanton, Edgar Rice Burroughs, Mark And...

In [29]:
movieCredit.head()

,movie_id,title,cast,directing_crew,writing_crew
0,19995,Avatar,"Alicia Vela-Bailey, Allan Henry, Anthony Ingru...",James Cameron,James Cameron
1,285,Pirates of the Caribbean: At World's End,"Andy Beckwith, Angus Barnett, Bill Nighy, Chow...",Gore Verbinski,"Ted Elliott, Terry Rossio"
2,206647,Spectre,"Adam McGrady, Adel Bencherif, Adriana Paz, Ale...",Sam Mendes,"Ian Fleming, Jez Butterworth, John Logan, Neal..."
3,49026,The Dark Knight Rises,"Aidan Gillen, Aja Evans, Aldous Davidson, Alex...",Christopher Nolan,"Bob Kane, Christopher Nolan, David S. Goyer, J..."
4,49529,John Carter,"Amanda Clayton, Arkie Reece, Bryan Cranston, C...",Andrew Stanton,"Andrew Stanton, Edgar Rice Burroughs, Mark And..."

In [30]:
movies = pd.read_csv('tmdb_5000_movies.csv', engine='python', skipinitialspace=True)
print("Loaded 'tmdb_5000_movies.csv' into 'movies' DataFrame.")
print(movies.head())

Loaded 'tmdb_5000_movies.csv' into 'movies' DataFrame.
      budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995
1  http://disney.go.com/disneypictures/pirates/     285
2   http://www.sonypictures.com/movies/spectre/  206647
3            http://www.thedarkknightrises.com/   49026
4          http://movies.disney.com/john-carter   49529

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en
4  [{"id": 818, "name": "based on novel"}, {"id":...                en

                             original_title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577
1  Captain Barbossa, long believed to be dead, ha...  139.082615
2  A cryptic message from Bond’s past sends him o...  107.376788
3  Following the death of District Attorney Harve...  112.312950
4  John Carter is a war-weary, former military ca...   43.926995

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...
3  [{"name": "Legendary Pictures", "id": 923}, {"...
4        [{"name": "Walt Disney Pictures", "id": 2}]

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   10-12-2009  2787965087
1  [{"iso_3166_1": "US", "name": "United States o...   19-05-2007   961000000
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   26-10-2015   880674609
3  [{"iso_3166_1": "US", "name": "United States o...   16-07-2012  1084939099
4  [{"iso_3166_1": "US", "name": "United States o...   07-03-2012   284139100

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released

                                          tagline  \
0                     Enter the World of Pandora.
1  At the end of the world, the adventure begins.
2                           A Plan No One Escapes
3                                 The Legend Ends
4            Lost in our world, found in another.

                                      title  vote_average  vote_count
0                                    Avatar           7.2       11800
1  Pirates of the Caribbean: At World's End           6.9        4500
2                                   Spectre           6.3        4466
3                     The Dark Knight Rises           7.6        9106
4                               John Carter           6.1        2124

In [31]:
movies = movies[['genres', 'id', 'keywords', 'original_title', 'overview', 'production_companies']]
print("Selected specified columns from the 'movies' DataFrame.")
print(movies.head())

Selected specified columns from the 'movies' DataFrame.
                                              genres      id  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   19995
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...     285
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...  206647
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   49026
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   49529

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...
4  [{"id": 818, "name": "based on novel"}, {"id":...

                             original_title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...
1  Captain Barbossa, long believed to be dead, ha...
2  A cryptic message from Bond’s past sends him o...
3  Following the death of District Attorney Harve...
4  John Carter is a war-weary, former military ca...

                                production_companies
0  [{"name": "Ingenious Film Partners", "id": 289...
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...
3  [{"name": "Legendary Pictures", "id": 923}, {"...
4        [{"name": "Walt Disney Pictures", "id": 2}]

In [32]:
import json

def extract_names_from_json(json_str):
    try:
        if not isinstance(json_str, str):
            return ''
        list_of_dicts = json.loads(json_str)
        names = [d['name'] for d in list_of_dicts if 'name' in d]
        return ', '.join(names)
    except (json.JSONDecodeError, TypeError):
        return ''
    except Exception as e:
        print(f"Error processing JSON string: {json_str} - {e}")
        return ''

movies['genres'] = movies['genres'].apply(extract_names_from_json)
print("Extracted names from 'genres' column.")
movies['keywords'] = movies['keywords'].apply(extract_names_from_json)
print("Extracted names from 'keywords' column.")
movies['production_companies'] = movies['production_companies'].apply(extract_names_from_json)
print("Extracted names from 'production_companies' column.")

print("\nUpdated 'movies' DataFrame head:")
print(movies.head())

Extracted names from 'genres' column.
Extracted names from 'keywords' column.
Extracted names from 'production_companies' column.

Updated 'movies' DataFrame head:
                                        genres      id  \
0  Action, Adventure, Fantasy, Science Fiction   19995
1                   Adventure, Fantasy, Action     285
2                     Action, Adventure, Crime  206647
3               Action, Crime, Drama, Thriller   49026
4           Action, Adventure, Science Fiction   49529

                                            keywords  \
0  culture clash, future, space war, space colony...
1  ocean, drug abuse, exotic island, east india t...
2  spy, based on novel, secret agent, sequel, mi6...
3  dc comics, crime fighter, terrorist, secret id...
4  based on novel, mars, medallion, space travel,...

                             original_title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...
1  Captain Barbossa, long believed to be dead, ha...
2  A cryptic message from Bond’s past sends him o...
3  Following the death of District Attorney Harve...
4  John Carter is a war-weary, former military ca...

                                production_companies
0  Ingenious Film Partners, Twentieth Century Fox...
1  Walt Disney Pictures, Jerry Bruckheimer Films,...
2                     Columbia Pictures, Danjaq, B24
3  Legendary Pictures, Warner Bros., DC Entertain...
4                               Walt Disney Pictures

In [33]:
movies.drop('production_companies', axis=1, inplace=True)
print("Dropped 'production_companies' column from the movies DataFrame.")
print(movies.head())

Dropped 'production_companies' column from the movies DataFrame.
                                        genres      id  \
0  Action, Adventure, Fantasy, Science Fiction   19995
1                   Adventure, Fantasy, Action     285
2                     Action, Adventure, Crime  206647
3               Action, Crime, Drama, Thriller   49026
4           Action, Adventure, Science Fiction   49529

                                            keywords  \
0  culture clash, future, space war, space colony...
1  ocean, drug abuse, exotic island, east india t...
2  spy, based on novel, secret agent, sequel, mi6...
3  dc comics, crime fighter, terrorist, secret id...
4  based on novel, mars, medallion, space travel,...

                             original_title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                            overview
0  In the 22nd century, a paraplegic Marine is di...
1  Captain Barbossa, long believed to be dead, ha...
2  A cryptic message from Bond’s past sends him o...
3  Following the death of District Attorney Harve...
4  John Carter is a war-weary, former military ca...

In [34]:
movieCredit['movie_id'] = pd.to_numeric(movieCredit['movie_id'], errors='coerce')
movieCredit.dropna(subset=['movie_id'], inplace=True)
movieCredit['movie_id'] = movieCredit['movie_id'].astype(int)
merged_movies = pd.merge(movieCredit, movies, left_on='movie_id', right_on='id', how='inner')
print("Merged 'movieCredit' and 'movies' DataFrames into 'merged_movies'.")
print(merged_movies.head())

Merged 'movieCredit' and 'movies' DataFrames into 'merged_movies'.
   movie_id                                     title  \
0     19995                                    Avatar
1       285  Pirates of the Caribbean: At World's End
2    206647                                   Spectre
3     49026                     The Dark Knight Rises
4     49529                               John Carter

                                                cast     directing_crew  \
0  Alicia Vela-Bailey, Allan Henry, Anthony Ingru...      James Cameron
1  Andy Beckwith, Angus Barnett, Bill Nighy, Chow...     Gore Verbinski
2  Adam McGrady, Adel Bencherif, Adriana Paz, Ale...         Sam Mendes
3  Aidan Gillen, Aja Evans, Aldous Davidson, Alex...  Christopher Nolan
4  Amanda Clayton, Arkie Reece, Bryan Cranston, C...     Andrew Stanton

                                        writing_crew  \
0                                      James Cameron
1                          Ted Elliott, Terry Rossio
2  Ian Fleming, Jez Butterworth, John Logan, Neal...
3  Bob Kane, Christopher Nolan, David S. Goyer, J...
4  Andrew Stanton, Edgar Rice Burroughs, Mark And...

                                        genres      id  \
0  Action, Adventure, Fantasy, Science Fiction   19995
1                   Adventure, Fantasy, Action     285
2                     Action, Adventure, Crime  206647
3               Action, Crime, Drama, Thriller   49026
4           Action, Adventure, Science Fiction   49529

                                            keywords  \
0  culture clash, future, space war, space colony...
1  ocean, drug abuse, exotic island, east india t...
2  spy, based on novel, secret agent, sequel, mi6...
3  dc comics, crime fighter, terrorist, secret id...
4  based on novel, mars, medallion, space travel,...

                             original_title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                            overview
0  In the 22nd century, a paraplegic Marine is di...
1  Captain Barbossa, long believed to be dead, ha...
2  A cryptic message from Bond’s past sends him o...
3  Following the death of District Attorney Harve...
4  John Carter is a war-weary, former military ca...

In [35]:
merged_movies.drop(columns=['id', 'original_title'], inplace=True)
merged_movies.rename(columns={'title': 'movie_name'}, inplace=True)
print("Removed 'id' and 'original_title' columns and renamed 'title' to 'movie_name'.")
print(merged_movies.head())

Removed 'id' and 'original_title' columns and renamed 'title' to 'movie_name'.
   movie_id                                movie_name  \
0     19995                                    Avatar
1       285  Pirates of the Caribbean: At World's End
2    206647                                   Spectre
3     49026                     The Dark Knight Rises
4     49529                               John Carter

                                                cast     directing_crew  \
0  Alicia Vela-Bailey, Allan Henry, Anthony Ingru...      James Cameron
1  Andy Beckwith, Angus Barnett, Bill Nighy, Chow...     Gore Verbinski
2  Adam McGrady, Adel Bencherif, Adriana Paz, Ale...         Sam Mendes
3  Aidan Gillen, Aja Evans, Aldous Davidson, Alex...  Christopher Nolan
4  Amanda Clayton, Arkie Reece, Bryan Cranston, C...     Andrew Stanton

                                        writing_crew  \
0                                      James Cameron
1                          Ted Elliott, Terry Rossio
2  Ian Fleming, Jez Butterworth, John Logan, Neal...
3  Bob Kane, Christopher Nolan, David S. Goyer, J...
4  Andrew Stanton, Edgar Rice Burroughs, Mark And...

                                        genres  \
0  Action, Adventure, Fantasy, Science Fiction
1                   Adventure, Fantasy, Action
2                     Action, Adventure, Crime
3               Action, Crime, Drama, Thriller
4           Action, Adventure, Science Fiction

                                            keywords  \
0  culture clash, future, space war, space colony...
1  ocean, drug abuse, exotic island, east india t...
2  spy, based on novel, secret agent, sequel, mi6...
3  dc comics, crime fighter, terrorist, secret id...
4  based on novel, mars, medallion, space travel,...

                                            overview
0  In the 22nd century, a paraplegic Marine is di...
1  Captain Barbossa, long believed to be dead, ha...
2  A cryptic message from Bond’s past sends him o...
3  Following the death of District Attorney Harve...
4  John Carter is a war-weary, former military ca...

In [36]:
duplicate_rows = merged_movies[merged_movies.duplicated()]

if not duplicate_rows.empty:
    print(f"Found {len(duplicate_rows)} duplicate rows in `merged_movies`:")
    display(duplicate_rows)
else:
    print("No duplicate rows found in `merged_movies`.")

No duplicate rows found in `merged_movies`.

In [37]:
print("Missing values in merged_movies DataFrame:")
print(merged_movies.isnull().sum())

Missing values in merged_movies DataFrame:
movie_id          0
movie_name        0
cast              0
directing_crew    0
writing_crew      0
genres            0
keywords          0
overview          4
dtype: int64

In [38]:
merged_movies['overview'] = merged_movies['overview'].fillna('')
print("Filled missing values in 'overview' column with an empty string.")
print(merged_movies.isnull().sum())

Filled missing values in 'overview' column with an empty string.
movie_id          0
movie_name        0
cast              0
directing_crew    0
writing_crew      0
genres            0
keywords          0
overview          0
dtype: int64

In [39]:
merged_movies['overview'].fillna('', inplace=True)
print("Filled missing values in 'overview' column with an empty string.")
print(merged_movies.isnull().sum())

Filled missing values in 'overview' column with an empty string.
movie_id          0
movie_name        0
cast              0
directing_crew    0
writing_crew      0
genres            0
keywords          0
overview          0
dtype: int64

/tmp/ipykernel_971/1249451184.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_movies['overview'].fillna('', inplace=True)

In [40]:
def remove_spaces_from_names(names_str):
    if not isinstance(names_str, str) or not names_str.strip():
        return ''
    names = [name.replace(' ', '') for name in names_str.split(',')]
    return ','.join(names)

columns_to_process = ['cast', 'directing_crew', 'writing_crew', 'genres', 'keywords']

for col in columns_to_process:
    merged_movies[col] = merged_movies[col].apply(remove_spaces_from_names)
    print(f"Removed spaces from names in '{col}' column.")

print("\nUpdated 'merged_movies' DataFrame head:")
print(merged_movies.head())

Removed spaces from names in 'cast' column.
Removed spaces from names in 'directing_crew' column.
Removed spaces from names in 'writing_crew' column.
Removed spaces from names in 'genres' column.
Removed spaces from names in 'keywords' column.

Updated 'merged_movies' DataFrame head:
   movie_id                                movie_name  \
0     19995                                    Avatar
1       285  Pirates of the Caribbean: At World's End
2    206647                                   Spectre
3     49026                     The Dark Knight Rises
4     49529                               John Carter

                                                cast    directing_crew  \
0  AliciaVela-Bailey,AllanHenry,AnthonyIngruber,A...      JamesCameron
1  AndyBeckwith,AngusBarnett,BillNighy,ChowYun-fa...     GoreVerbinski
2  AdamMcGrady,AdelBencherif,AdrianaPaz,Alessandr...         SamMendes
3  AidanGillen,AjaEvans,AldousDavidson,AlexKruz,A...  ChristopherNolan
4  AmandaClayton,ArkieReece,BryanCranston,Christo...     AndrewStanton

                                        writing_crew  \
0                                       JamesCameron
1                             TedElliott,TerryRossio
2  IanFleming,JezButterworth,JohnLogan,NealPurvis...
3  BobKane,ChristopherNolan,DavidS.Goyer,Jonathan...
4  AndrewStanton,EdgarRiceBurroughs,MarkAndrews,M...

                                    genres  \
0  Action,Adventure,Fantasy,ScienceFiction
1                 Adventure,Fantasy,Action
2                   Action,Adventure,Crime
3              Action,Crime,Drama,Thriller
4          Action,Adventure,ScienceFiction

                                            keywords  \
0  cultureclash,future,spacewar,spacecolony,socie...
1  ocean,drugabuse,exoticisland,eastindiatradingc...
2  spy,basedonnovel,secretagent,sequel,mi6,britis...
3  dccomics,crimefighter,terrorist,secretidentity...
4  basedonnovel,mars,medallion,spacetravel,prince...

                                            overview
0  In the 22nd century, a paraplegic Marine is di...
1  Captain Barbossa, long believed to be dead, ha...
2  A cryptic message from Bond’s past sends him o...
3  Following the death of District Attorney Harve...
4  John Carter is a war-weary, former military ca...

In [41]:
merged_movies['tags'] = merged_movies.apply(lambda row:
    ' '.join(
        (row['genres'].split(',') * 3 if row['genres'] else []) +
        (row['keywords'].split(',') * 3 if row['keywords'] else []) +
        (row['cast'].split(',') * 2 if row['cast'] else []) +
        (row['directing_crew'].split(',') * 2 if row['directing_crew'] else []) +
        (row['writing_crew'].split(',') * 1 if row['writing_crew'] else []) +
        (row['overview'].split() if row['overview'] else [])
    ),
    axis=1
)

print("Updated 'tags' column with proper spacing between elements.")
print(merged_movies[['movie_name', 'tags']].head())

Updated 'tags' column with proper spacing between elements.
                                 movie_name  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                                tags
0  Action Adventure Fantasy ScienceFiction Action...
1  Adventure Fantasy Action Adventure Fantasy Act...
2  Action Adventure Crime Action Adventure Crime ...
3  Action Crime Drama Thriller Action Crime Drama...
4  Action Adventure ScienceFiction Action Adventu...

In [42]:
print(merged_movies['tags'].dtype)
print(merged_movies['tags'].iloc[0])

object
Action Adventure Fantasy ScienceFiction Action Adventure Fantasy ScienceFiction Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d AliciaVela-Bailey AllanHenry AnthonyIngruber AprilMarieThomas AshleyJeffery AustinWilson BrandonJelkes BravitaA.Threatt CCHPounder CarvonFutrell ChrisMala ChristaOliver ChristopherNolen ColinBleasdale CullenB.Madden DavidVanHorn DeanKnowsley DebraWilson DileepRao FrankieTorres GarethRuck GerryBlair GiovanniRibisi HanniyahMuhammad IlramChoi JacobTomuri JahnelCurfman JamesGaylyn JamesPatrickPitt JamieHarrison JasonWhyte JodieLandau JodieTaylor JoelDavidMoore JonCurry JosephBradyMadden JosephMika-Hunt JuleneRenee JulieLamm KaiPantano KellyKilgour KelsonHenderson KevinDorman KylaWarren LazAlonso LisaRoumain LoganPithyou LucyBriant LukeHawker MattClayton MattGerald MatthewChamberlain MelvinLenoClarkIII MicahMoch MichaelBlain-Rozgay MichelleRodriguez MikeBodnar NathanMeister NicoleDionne NikieZambo PaulYates PeterDillon PeterMensah Raja RhianSheehan RichardWhiteside SamWorthington SaraWilson ScottLawrence SeanAnthonyMoran SeanPatrickMurphy SigourneyWeaver SoniaYee StephenLang StuartPollock T.J.Storm TamicaWashington-Miller TaylorKibby TerryNotary WesStudi WoodySchultz WrayWilson ZoeSaldana AliciaVela-Bailey AllanHenry AnthonyIngruber AprilMarieThomas AshleyJeffery AustinWilson BrandonJelkes BravitaA.Threatt CCHPounder CarvonFutrell ChrisMala ChristaOliver ChristopherNolen ColinBleasdale CullenB.Madden DavidVanHorn DeanKnowsley DebraWilson DileepRao FrankieTorres GarethRuck GerryBlair GiovanniRibisi HanniyahMuhammad IlramChoi JacobTomuri JahnelCurfman JamesGaylyn JamesPatrickPitt JamieHarrison JasonWhyte JodieLandau JodieTaylor JoelDavidMoore JonCurry JosephBradyMadden JosephMika-Hunt JuleneRenee JulieLamm KaiPantano KellyKilgour KelsonHenderson KevinDorman KylaWarren LazAlonso LisaRoumain LoganPithyou LucyBriant LukeHawker MattClayton MattGerald MatthewChamberlain MelvinLenoClarkIII MicahMoch MichaelBlain-Rozgay MichelleRodriguez MikeBodnar NathanMeister NicoleDionne NikieZambo PaulYates PeterDillon PeterMensah Raja RhianSheehan RichardWhiteside SamWorthington SaraWilson ScottLawrence SeanAnthonyMoran SeanPatrickMurphy SigourneyWeaver SoniaYee StephenLang StuartPollock T.J.Storm TamicaWashington-Miller TaylorKibby TerryNotary WesStudi WoodySchultz WrayWilson ZoeSaldana JamesCameron JamesCameron JamesCameron In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.

In [43]:
print("Dropped all columns except 'movie_name' and 'tags'.")
print(merged_movies.head())

Dropped all columns except 'movie_name' and 'tags'.
   movie_id                                movie_name  \
0     19995                                    Avatar
1       285  Pirates of the Caribbean: At World's End
2    206647                                   Spectre
3     49026                     The Dark Knight Rises
4     49529                               John Carter

                                                cast    directing_crew  \
0  AliciaVela-Bailey,AllanHenry,AnthonyIngruber,A...      JamesCameron
1  AndyBeckwith,AngusBarnett,BillNighy,ChowYun-fa...     GoreVerbinski
2  AdamMcGrady,AdelBencherif,AdrianaPaz,Alessandr...         SamMendes
3  AidanGillen,AjaEvans,AldousDavidson,AlexKruz,A...  ChristopherNolan
4  AmandaClayton,ArkieReece,BryanCranston,Christo...     AndrewStanton

                                        writing_crew  \
0                                       JamesCameron
1                             TedElliott,TerryRossio
2  IanFleming,JezButterworth,JohnLogan,NealPurvis...
3  BobKane,ChristopherNolan,DavidS.Goyer,Jonathan...
4  AndrewStanton,EdgarRiceBurroughs,MarkAndrews,M...

                                    genres  \
0  Action,Adventure,Fantasy,ScienceFiction
1                 Adventure,Fantasy,Action
2                   Action,Adventure,Crime
3              Action,Crime,Drama,Thriller
4          Action,Adventure,ScienceFiction

                                            keywords  \
0  cultureclash,future,spacewar,spacecolony,socie...
1  ocean,drugabuse,exoticisland,eastindiatradingc...
2  spy,basedonnovel,secretagent,sequel,mi6,britis...
3  dccomics,crimefighter,terrorist,secretidentity...
4  basedonnovel,mars,medallion,spacetravel,prince...

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...
1  Captain Barbossa, long believed to be dead, ha...
2  A cryptic message from Bond’s past sends him o...
3  Following the death of District Attorney Harve...
4  John Carter is a war-weary, former military ca...

                                                tags
0  Action Adventure Fantasy ScienceFiction Action...
1  Adventure Fantasy Action Adventure Fantasy Act...
2  Action Adventure Crime Action Adventure Crime ...
3  Action Crime Drama Thriller Action Crime Drama...
4  Action Adventure ScienceFiction Action Adventu...

In [44]:
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

In [45]:
# Download NLTK stopwords if not already downloaded
try:
    stopwords.words('english')
except LookupError:
    nltk.download('stopwords')
print("NLTK stopwords are ready.")

NLTK stopwords are ready.

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [46]:
merged_movies['tags'] = merged_movies['tags'].str.lower()
print("Converted 'tags' column to lowercase.")
print(merged_movies.head())

Converted 'tags' column to lowercase.
   movie_id                                movie_name  \
0     19995                                    Avatar
1       285  Pirates of the Caribbean: At World's End
2    206647                                   Spectre
3     49026                     The Dark Knight Rises
4     49529                               John Carter

                                                cast    directing_crew  \
0  AliciaVela-Bailey,AllanHenry,AnthonyIngruber,A...      JamesCameron
1  AndyBeckwith,AngusBarnett,BillNighy,ChowYun-fa...     GoreVerbinski
2  AdamMcGrady,AdelBencherif,AdrianaPaz,Alessandr...         SamMendes
3  AidanGillen,AjaEvans,AldousDavidson,AlexKruz,A...  ChristopherNolan
4  AmandaClayton,ArkieReece,BryanCranston,Christo...     AndrewStanton

                                        writing_crew  \
0                                       JamesCameron
1                             TedElliott,TerryRossio
2  IanFleming,JezButterworth,JohnLogan,NealPurvis...
3  BobKane,ChristopherNolan,DavidS.Goyer,Jonathan...
4  AndrewStanton,EdgarRiceBurroughs,MarkAndrews,M...

                                    genres  \
0  Action,Adventure,Fantasy,ScienceFiction
1                 Adventure,Fantasy,Action
2                   Action,Adventure,Crime
3              Action,Crime,Drama,Thriller
4          Action,Adventure,ScienceFiction

                                            keywords  \
0  cultureclash,future,spacewar,spacecolony,socie...
1  ocean,drugabuse,exoticisland,eastindiatradingc...
2  spy,basedonnovel,secretagent,sequel,mi6,britis...
3  dccomics,crimefighter,terrorist,secretidentity...
4  basedonnovel,mars,medallion,spacetravel,prince...

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...
1  Captain Barbossa, long believed to be dead, ha...
2  A cryptic message from Bond’s past sends him o...
3  Following the death of District Attorney Harve...
4  John Carter is a war-weary, former military ca...

                                                tags
0  action adventure fantasy sciencefiction action...
1  adventure fantasy action adventure fantasy act...
2  action adventure crime action adventure crime ...
3  action crime drama thriller action crime drama...
4  action adventure sciencefiction action adventu...

In [47]:
stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    return ' '.join([word for word in str(text).split() if word not in stop_words])

merged_movies['tags'] = merged_movies['tags'].apply(remove_stopwords)
print("Removed stopwords from 'tags' column.")
print(merged_movies.head())

Removed stopwords from 'tags' column.
   movie_id                                movie_name  \
0     19995                                    Avatar
1       285  Pirates of the Caribbean: At World's End
2    206647                                   Spectre
3     49026                     The Dark Knight Rises
4     49529                               John Carter

                                                cast    directing_crew  \
0  AliciaVela-Bailey,AllanHenry,AnthonyIngruber,A...      JamesCameron
1  AndyBeckwith,AngusBarnett,BillNighy,ChowYun-fa...     GoreVerbinski
2  AdamMcGrady,AdelBencherif,AdrianaPaz,Alessandr...         SamMendes
3  AidanGillen,AjaEvans,AldousDavidson,AlexKruz,A...  ChristopherNolan
4  AmandaClayton,ArkieReece,BryanCranston,Christo...     AndrewStanton

                                        writing_crew  \
0                                       JamesCameron
1                             TedElliott,TerryRossio
2  IanFleming,JezButterworth,JohnLogan,NealPurvis...
3  BobKane,ChristopherNolan,DavidS.Goyer,Jonathan...
4  AndrewStanton,EdgarRiceBurroughs,MarkAndrews,M...

                                    genres  \
0  Action,Adventure,Fantasy,ScienceFiction
1                 Adventure,Fantasy,Action
2                   Action,Adventure,Crime
3              Action,Crime,Drama,Thriller
4          Action,Adventure,ScienceFiction

                                            keywords  \
0  cultureclash,future,spacewar,spacecolony,socie...
1  ocean,drugabuse,exoticisland,eastindiatradingc...
2  spy,basedonnovel,secretagent,sequel,mi6,britis...
3  dccomics,crimefighter,terrorist,secretidentity...
4  basedonnovel,mars,medallion,spacetravel,prince...

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...
1  Captain Barbossa, long believed to be dead, ha...
2  A cryptic message from Bond’s past sends him o...
3  Following the death of District Attorney Harve...
4  John Carter is a war-weary, former military ca...

                                                tags
0  action adventure fantasy sciencefiction action...
1  adventure fantasy action adventure fantasy act...
2  action adventure crime action adventure crime ...
3  action crime drama thriller action crime drama...
4  action adventure sciencefiction action adventu...

In [48]:
tfidf = TfidfVectorizer(max_features=5000)
tfidf_matrix = tfidf.fit_transform(merged_movies['tags'])

print("TF-IDF vectorization applied to 'tags' column.")
print(f"Shape of TF-IDF matrix: {tfidf_matrix.shape}")

TF-IDF vectorization applied to 'tags' column.
Shape of TF-IDF matrix: (4803, 5000)

In [49]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim = cosine_similarity(tfidf_matrix)
print("Cosine similarity matrix calculated.")
print(f"Shape of cosine similarity matrix: {cosine_sim.shape}")

Cosine similarity matrix calculated.
Shape of cosine similarity matrix: (4803, 4803)

In [50]:
def recommend_movies(movie_title, merged_movies_df, cosine_sim_matrix, num_recommendations=5):
    # Get the index of the movie that matches the title, allowing for partial, case-insensitive matching
    try:
        # Find all movies that partially match the title (case-insensitive)
        matching_movies = merged_movies_df[merged_movies_df['movie_name'].str.contains(movie_title.strip(), case=False, na=False)]
        if matching_movies.empty:
            return f"Movie '{movie_title}' not found in the dataset."
        # Get the index of the first matching movie
        idx = matching_movies.index[0]
    except IndexError:
        return f"Movie '{movie_title}' not found in the dataset."

    # Get the cosine similarity scores for that movie with all other movies
    sim_scores = list(enumerate(cosine_sim_matrix[idx]))

    # Sort the movies based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the `num_recommendations` most similar movies (excluding itself)
    sim_scores = sim_scores[1:num_recommendations+1]

    # Get the movie indices and their similarity scores
    movie_indices = [i[0] for i in sim_scores]
    movie_similarities = [i[1] for i in sim_scores]

    # Return the top `num_recommendations` similar movies with their scores
    recommendations = pd.DataFrame({
        'Recommended Movie': merged_movies_df['movie_name'].iloc[movie_indices].values,
        'Similarity Score': movie_similarities
    })
    return recommendations

In [52]:
# import ipywidgets as widgets
# from IPython.display import display, clear_output
# from ipywidgets import Output

# # Create an output widget
# output_widget = Output()

# def on_movie_submit(sender):
#     with output_widget:
#         output_widget.clear_output(wait=True)
#         movie_title = sender.value
#         if movie_title:
#             recommendations = recommend_movies(movie_title, merged_movies, cosine_sim, 5)
#             print(f"\nRecommendations for '{movie_title}':")
#             print(recommendations)
#         else:
#             print("\nPlease enter a movie title.")

# movie_input = widgets.Text(
#     value='',
#     placeholder='Enter movie title',
#     description='Movie Title:',
#     disabled=False
# )

# # Link the function to the widget's value change (on submit/enter)
# movie_input.on_submit(on_movie_submit)

# print("Enter a movie title in the box below and press Enter for recommendations.")
# display(movie_input, output_widget)